n1 = int (input("Por favor, digite o primeiro número inteiro: "))
n2 = int (input("Por favor, digite o segundo número inteiro: "))
n3 = int (input("Por favor, digite o terceiro número inteiro: "))
n4 = int (input("Por favor, digite o quarto número inteiro: "))
n5 = int (input("Por favor, digite o quarto número inteiro: "))
n6 = int (input("Por favor, digite o sexto número inteiro: "))
n7 = int (input("Por favor, digite o sétimo número inteiro: "))
n8 = int (input("Por favor, digite o oitavo número inteiro: "))
n9 = int (input("Por favor, digite o nono número inteiro: "))
n10 = int (input("Por favor, digite o décimo número inteiro: "))
n11 = int (input("Por favor, digite o décimo primeiro número inteiro: "))

saida1=float(n1+n2+n3)
saida2=float(n5/n4)
saida3=float(n7-n6)
saida4=float(n8+n9+n10)
saida5=float(saida4-saida3-saida2-saida1)
saida6=float(saida5*n11)
saida7=float(saida6/10)
saida8=float(saida7%10)

print ("Operações efetuada: \n{n1}+{n2}={saida1}\n{n5}/{n4}={saida2}\n{n7}-{n6}={saida3}\n{n8}+{n9}+{n10}={saida4}\n{saida4}-{saida3}-{saida2}-{saida1}= {saida5}\n{saida5}*{n11}={saida6}\nQuociente da divisão de {saida6}//10: {saida7}\nResto da divisão de {saida7}//10: {saida8} ".format( saida1=saida1, saida2=saida2,saida3=saida3,saida4=saida4, saida5=saida5,saida6=saida6,saida7=saida7,saida8=saida8,n1=n1,n2=n2,n3=n3,n4=n4,n5=n5,n6=n6,n7=n7,n8=n8,n9=n9,n10=n10,n11=n11))